//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY CHANGES.
        /// </summary>
        public static string AcceptChangesLabel {
            get {
                return ResourceManager.GetString("AcceptChangesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional points:.
        /// </summary>
        public static string AdditionalScoreLabel {
            get {
                return ResourceManager.GetString("AdditionalScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new players to DB?.
        /// </summary>
        public static string AddNewPlayersMessage {
            get {
                return ResourceManager.GetString("AddNewPlayersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game to DB?.
        /// </summary>
        public static string AddToDbMessage {
            get {
                return ResourceManager.GetString("AddToDbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLTIME.
        /// </summary>
        public static string AllTimeButton {
            get {
                return ResourceManager.GetString("AllTimeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. games count for all time rating:.
        /// </summary>
        public static string AllTimeGapLabel {
            get {
                return ResourceManager.GetString("AllTimeGapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply ratio for FIIM rating.
        /// </summary>
        public static string ApplyRatioLabel {
            get {
                return ResourceManager.GetString("ApplyRatioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup DB.
        /// </summary>
        public static string BackupDb {
            get {
                return ResourceManager.GetString("BackupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string BanHeader {
            get {
                return ResourceManager.GetString("BanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of disqualifications.
        /// </summary>
        public static string BanTooltip {
            get {
                return ResourceManager.GetString("BanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 1.
        /// </summary>
        public static string Best1 {
            get {
                return ResourceManager.GetString("Best1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 2.
        /// </summary>
        public static string Best2 {
            get {
                return ResourceManager.GetString("Best2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best 3.
        /// </summary>
        public static string Best3 {
            get {
                return ResourceManager.GetString("Best3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BestWay.
        /// </summary>
        public static string BestChoiceHeader {
            get {
                return ResourceManager.GetString("BestChoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best choice:.
        /// </summary>
        public static string BestChoiceLabel {
            get {
                return ResourceManager.GetString("BestChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full &apos;best choice&apos; count.
        /// </summary>
        public static string BestChoiceTooltip {
            get {
                return ResourceManager.GetString("BestChoiceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST.
        /// </summary>
        public static string BestHeader {
            get {
                return ResourceManager.GetString("BestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best player.
        /// </summary>
        public static string BestPlayer {
            get {
                return ResourceManager.GetString("BestPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BestPlayer.
        /// </summary>
        public static string BestPlayerHeader {
            get {
                return ResourceManager.GetString("BestPlayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times voted as best player.
        /// </summary>
        public static string BestPlayerTooltip {
            get {
                return ResourceManager.GetString("BestPlayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia.
        /// </summary>
        public static string BlackLabel {
            get {
                return ResourceManager.GetString("BlackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackGuess.
        /// </summary>
        public static string BlackUgadHeader {
            get {
                return ResourceManager.GetString("BlackUgadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of black wins in guessing.
        /// </summary>
        public static string BlackUgadTooltip {
            get {
                return ResourceManager.GetString("BlackUgadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLTIME RATING.
        /// </summary>
        public static string ChAllTimeHeader {
            get {
                return ResourceManager.GetString("ChAllTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application have to be reloaded. Restart now?.
        /// </summary>
        public static string ChangeLanguageMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change nick:.
        /// </summary>
        public static string ChangeNickLabel {
            get {
                return ResourceManager.GetString("ChangeNickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKS.
        /// </summary>
        public static string CheckWindowTitle {
            get {
                return ResourceManager.GetString("CheckWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEASON RATING.
        /// </summary>
        public static string ChSeasonHeader {
            get {
                return ResourceManager.GetString("ChSeasonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIES RATING.
        /// </summary>
        public static string ChSeriesHeader {
            get {
                return ResourceManager.GetString("ChSeriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK RATING.
        /// </summary>
        public static string ChWeekHeader {
            get {
                return ResourceManager.GetString("ChWeekHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 games without fouls.
        /// </summary>
        public static string ComboWfText {
            get {
                return ResourceManager.GetString("ComboWfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboWin.
        /// </summary>
        public static string ComboWinLabel {
            get {
                return ResourceManager.GetString("ComboWinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 wins in a row.
        /// </summary>
        public static string ComboWinText {
            get {
                return ResourceManager.GetString("ComboWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        public static string CountButton {
            get {
                return ResourceManager.GetString("CountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Infographics.
        /// </summary>
        public static string CreateInfographics {
            get {
                return ResourceManager.GetString("CreateInfographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new protocol?.
        /// </summary>
        public static string CreateNewProtocolMessage {
            get {
                return ResourceManager.GetString("CreateNewProtocolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Successfully copied to file.
        /// </summary>
        public static string DbCopiedMessage {
            get {
                return ResourceManager.GetString("DbCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating DB backup:.
        /// </summary>
        public static string DbCopyErrorMessage {
            get {
                return ResourceManager.GetString("DbCopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB was changed.
        /// </summary>
        public static string DbRefreshedMessage {
            get {
                return ResourceManager.GetString("DbRefreshedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB was successfully changed..
        /// </summary>
        public static string DbSuccessMessage {
            get {
                return ResourceManager.GetString("DbSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqualify player #.
        /// </summary>
        public static string Disqualify {
            get {
                return ResourceManager.GetString("Disqualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISQUALIFY.
        /// </summary>
        public static string DisqualifyLabel {
            get {
                return ResourceManager.GetString("DisqualifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don.
        /// </summary>
        public static string Don {
            get {
                return ResourceManager.GetString("Don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON.
        /// </summary>
        public static string DonButton {
            get {
                return ResourceManager.GetString("DonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON CHECK:.
        /// </summary>
        public static string DonCheck {
            get {
                return ResourceManager.GetString("DonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;S CHECK.
        /// </summary>
        public static string DonCheckHeader {
            get {
                return ResourceManager.GetString("DonCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SEASON LABEL.
        /// </summary>
        public static string DropSeasonLabel {
            get {
                return ResourceManager.GetString("DropSeasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SERIES LABEL.
        /// </summary>
        public static string DropSeriesLabel {
            get {
                return ResourceManager.GetString("DropSeriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win series.
        /// </summary>
        public static string EpicFwText {
            get {
                return ResourceManager.GetString("EpicFwText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpicSeries.
        /// </summary>
        public static string EpicSeriesLabel {
            get {
                return ResourceManager.GetString("EpicSeriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpicW/F.
        /// </summary>
        public static string EpicWfLabel {
            get {
                return ResourceManager.GetString("EpicWfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpicWin.
        /// </summary>
        public static string EpicWinLabel {
            get {
                return ResourceManager.GetString("EpicWinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 wins is a row.
        /// </summary>
        public static string EpicWinText {
            get {
                return ResourceManager.GetString("EpicWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting complete.
        /// </summary>
        public static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE COM:.
        /// </summary>
        public static string FalseCom {
            get {
                return ResourceManager.GetString("FalseCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string FemaleLabel {
            get {
                return ResourceManager.GetString("FemaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOULS.
        /// </summary>
        public static string FoulsHeader {
            get {
                return ResourceManager.GetString("FoulsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of fouls.
        /// </summary>
        public static string FoulsTooltip {
            get {
                return ResourceManager.GetString("FoulsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game series.
        /// </summary>
        public static string GameSeries {
            get {
                return ResourceManager.GetString("GameSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GamesHeader {
            get {
                return ResourceManager.GetString("GamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES:.
        /// </summary>
        public static string GamesLabel {
            get {
                return ResourceManager.GetString("GamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games count.
        /// </summary>
        public static string GamesTooltip {
            get {
                return ResourceManager.GetString("GamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Charts.
        /// </summary>
        public static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string InfoAverage {
            get {
                return ResourceManager.GetString("InfoAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string InfoBan {
            get {
                return ResourceManager.GetString("InfoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string InfoBest {
            get {
                return ResourceManager.GetString("InfoBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string InfoBlack {
            get {
                return ResourceManager.GetString("InfoBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maf.
        /// </summary>
        public static string InfoBlackSlice {
            get {
                return ResourceManager.GetString("InfoBlackSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string InfoBlackWins {
            get {
                return ResourceManager.GetString("InfoBlackWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratio.
        /// </summary>
        public static string InfoCheck {
            get {
                return ResourceManager.GetString("InfoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string InfoClear {
            get {
                return ResourceManager.GetString("InfoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black wins.
        /// </summary>
        public static string InfoClearBlack {
            get {
                return ResourceManager.GetString("InfoClearBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red wins.
        /// </summary>
        public static string InfoClearRed {
            get {
                return ResourceManager.GetString("InfoClearRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don.
        /// </summary>
        public static string InfoDon {
            get {
                return ResourceManager.GetString("InfoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don.
        /// </summary>
        public static string InfoDonSlice {
            get {
                return ResourceManager.GetString("InfoDonSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string InfoDonWins {
            get {
                return ResourceManager.GetString("InfoDonWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False com.
        /// </summary>
        public static string InfoFc {
            get {
                return ResourceManager.GetString("InfoFc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string InfoFcWins {
            get {
                return ResourceManager.GetString("InfoFcWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first night.
        /// </summary>
        public static string InfoFirstNight {
            get {
                return ResourceManager.GetString("InfoFirstNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fouls.
        /// </summary>
        public static string InfoFouls {
            get {
                return ResourceManager.GetString("InfoFouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal infographics.
        /// </summary>
        public static string InfographicsTooltip {
            get {
                return ResourceManager.GetString("InfographicsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guessing.
        /// </summary>
        public static string InfoInUgad {
            get {
                return ResourceManager.GetString("InfoInUgad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black in.
        /// </summary>
        public static string InfoInUgadBlack {
            get {
                return ResourceManager.GetString("InfoInUgadBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red in.
        /// </summary>
        public static string InfoInUgadRed {
            get {
                return ResourceManager.GetString("InfoInUgadRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed in.
        /// </summary>
        public static string InfoKilled {
            get {
                return ResourceManager.GetString("InfoKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loses.
        /// </summary>
        public static string InfoLoseLabel {
            get {
                return ResourceManager.GetString("InfoLoseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string InfoPercent {
            get {
                return ResourceManager.GetString("InfoPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player.
        /// </summary>
        public static string InfoPlayer {
            get {
                return ResourceManager.GetString("InfoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string InfoRatio {
            get {
                return ResourceManager.GetString("InfoRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string InfoRed {
            get {
                return ResourceManager.GetString("InfoRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string InfoRedSlice {
            get {
                return ResourceManager.GetString("InfoRedSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string InfoRedWins {
            get {
                return ResourceManager.GetString("InfoRedWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string InfoSheriff {
            get {
                return ResourceManager.GetString("InfoSheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh.
        /// </summary>
        public static string InfoSheriffSlice {
            get {
                return ResourceManager.GetString("InfoSheriffSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string InfoWinLabel {
            get {
                return ResourceManager.GetString("InfoWinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff.
        /// </summary>
        public static string InfoWins {
            get {
                return ResourceManager.GetString("InfoWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1stKilled.
        /// </summary>
        public static string KilledFirstHeader {
            get {
                return ResourceManager.GetString("KilledFirstHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times was killed in first night.
        /// </summary>
        public static string KilledFirstTooltip {
            get {
                return ResourceManager.GetString("KilledFirstTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murders:.
        /// </summary>
        public static string KillsLabel {
            get {
                return ResourceManager.GetString("KillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string LoseHeader {
            get {
                return ResourceManager.GetString("LoseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loses count.
        /// </summary>
        public static string LoseTooltip {
            get {
                return ResourceManager.GetString("LoseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MaleLabel {
            get {
                return ResourceManager.GetString("MaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM:.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Member.
        /// </summary>
        public static string MemberTooltip {
            get {
                return ResourceManager.GetString("MemberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM:.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mishit.
        /// </summary>
        public static string Mishit {
            get {
                return ResourceManager.GetString("Mishit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Week.
        /// </summary>
        public static string NewWeek {
            get {
                return ResourceManager.GetString("NewWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week table not found.
        /// </summary>
        public static string NewWeekErrorMessage {
            get {
                return ResourceManager.GetString("NewWeekErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New week has been started.
        /// </summary>
        public static string NewWeekSuccessMessage {
            get {
                return ResourceManager.GetString("NewWeekSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick was changed.
        /// </summary>
        public static string NickChangedMessage {
            get {
                return ResourceManager.GetString("NickChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICK.
        /// </summary>
        public static string NickHeader {
            get {
                return ResourceManager.GetString("NickHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s Nick.
        /// </summary>
        public static string NickTooltip {
            get {
                return ResourceManager.GetString("NickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that are not in rating yet:.
        /// </summary>
        public static string NotInRating {
            get {
                return ResourceManager.GetString("NotInRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DB.
        /// </summary>
        public static string OpenDb {
            get {
                return ResourceManager.GetString("OpenDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        public static string PlayerButton {
            get {
                return ResourceManager.GetString("PlayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        public static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points was added.
        /// </summary>
        public static string PtsAddedMessage {
            get {
                return ResourceManager.GetString("PtsAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingHeader {
            get {
                return ResourceManager.GetString("RatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATING:.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s rating.
        /// </summary>
        public static string RatingTooltip {
            get {
                return ResourceManager.GetString("RatingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string RedLabel {
            get {
                return ResourceManager.GetString("RedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedGuess.
        /// </summary>
        public static string RedUgadHeader {
            get {
                return ResourceManager.GetString("RedUgadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of red wins in guessing.
        /// </summary>
        public static string RedUgadTooltip {
            get {
                return ResourceManager.GetString("RedUgadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RES.
        /// </summary>
        public static string ResultHeader {
            get {
                return ResourceManager.GetString("ResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLE.
        /// </summary>
        public static string RoleHeader {
            get {
                return ResourceManager.GetString("RoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar nicks entered.
        /// </summary>
        public static string SameNicksMessage {
            get {
                return ResourceManager.GetString("SameNicksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To DB.
        /// </summary>
        public static string SaveDb {
            get {
                return ResourceManager.GetString("SaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string ScoreHeader {
            get {
                return ResourceManager.GetString("ScoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTS:.
        /// </summary>
        public static string ScoreLabel {
            get {
                return ResourceManager.GetString("ScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of points.
        /// </summary>
        public static string ScoreTooltip {
            get {
                return ResourceManager.GetString("ScoreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEASON.
        /// </summary>
        public static string SeasonButton {
            get {
                return ResourceManager.GetString("SeasonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season table dropped.
        /// </summary>
        public static string SeasonDroppedMessage {
            get {
                return ResourceManager.GetString("SeasonDroppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEASON DYNAMICS:.
        /// </summary>
        public static string SeasonDynamicsLabel {
            get {
                return ResourceManager.GetString("SeasonDynamicsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. games count for season rating:.
        /// </summary>
        public static string SeasonGapLabel {
            get {
                return ResourceManager.GetString("SeasonGapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT WINNER.
        /// </summary>
        public static string SelectWinnerHeader {
            get {
                return ResourceManager.GetString("SelectWinnerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasa determine the winners.
        /// </summary>
        public static string SelectWinnerMessage {
            get {
                return ResourceManager.GetString("SelectWinnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIES.
        /// </summary>
        public static string SeriesButton {
            get {
                return ResourceManager.GetString("SeriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series table dropped.
        /// </summary>
        public static string SeriesDroppedMessage {
            get {
                return ResourceManager.GetString("SeriesDroppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIES DYNAMICS:.
        /// </summary>
        public static string SeriesDynamicsLabel {
            get {
                return ResourceManager.GetString("SeriesDynamicsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. games count for series rating:.
        /// </summary>
        public static string SeriesGapLabel {
            get {
                return ResourceManager.GetString("SeriesGapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string SeriesLabel {
            get {
                return ResourceManager.GetString("SeriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file doesn&apos;t exists.
        /// </summary>
        public static string SettingsNotFoundError {
            get {
                return ResourceManager.GetString("SettingsNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff.
        /// </summary>
        public static string Sheriff {
            get {
                return ResourceManager.GetString("Sheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHERIFF.
        /// </summary>
        public static string SheriffButton {
            get {
                return ResourceManager.GetString("SheriffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHERIFF&apos;S CHECK.
        /// </summary>
        public static string SheriffCheckHeader {
            get {
                return ResourceManager.GetString("SheriffCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHERIFF 1 NIGHT:.
        /// </summary>
        public static string SheriffFirstCheck {
            get {
                return ResourceManager.GetString("SheriffFirstCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff doesn&apos;t gets -1.
        /// </summary>
        public static string SheriffFirstNightLabel {
            get {
                return ResourceManager.GetString("SheriffFirstNightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHERIFF 2 NIGHT:.
        /// </summary>
        public static string SheriffSecondCheck {
            get {
                return ResourceManager.GetString("SheriffSecondCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllTime table doesn&apos;t exists.
        /// </summary>
        public static string StAllTimeError {
            get {
                return ResourceManager.GetString("StAllTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLTIME STATISTICS.
        /// </summary>
        public static string StAllTimeTitle {
            get {
                return ResourceManager.GetString("StAllTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new week?.
        /// </summary>
        public static string StartNewWeekMessage {
            get {
                return ResourceManager.GetString("StartNewWeekMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANS:.
        /// </summary>
        public static string StBans {
            get {
                return ResourceManager.GetString("StBans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total bans count.
        /// </summary>
        public static string StBansTooltip {
            get {
                return ResourceManager.GetString("StBansTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST PLAYER:.
        /// </summary>
        public static string StBestPlayer {
            get {
                return ResourceManager.GetString("StBestPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count of games where best player was determined.
        /// </summary>
        public static string StBestPlayersTotalTooltip {
            get {
                return ResourceManager.GetString("StBestPlayersTotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten players most often called the best.
        /// </summary>
        public static string StBestPlayerTooltip {
            get {
                return ResourceManager.GetString("StBestPlayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST CHOICE:.
        /// </summary>
        public static string StBestWay {
            get {
                return ResourceManager.GetString("StBestWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that are often killed in the first night.
        /// </summary>
        public static string StBestWayListTooltip {
            get {
                return ResourceManager.GetString("StBestWayListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count of games where full best choice was determined.
        /// </summary>
        public static string StBestWayTooltip {
            get {
                return ResourceManager.GetString("StBestWayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string StBlackLabel {
            get {
                return ResourceManager.GetString("StBlackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string StBlackSlice1 {
            get {
                return ResourceManager.GetString("StBlackSlice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string StBlackSlice2 {
            get {
                return ResourceManager.GetString("StBlackSlice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string StClearLabel {
            get {
                return ResourceManager.GetString("StClearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON WINS:.
        /// </summary>
        public static string StDonWins {
            get {
                return ResourceManager.GetString("StDonWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders by best win/lose ratio when playing as Don.
        /// </summary>
        public static string StDonWinsTooltip {
            get {
                return ResourceManager.GetString("StDonWinsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE COM:.
        /// </summary>
        public static string StFalseCom {
            get {
                return ResourceManager.GetString("StFalseCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most successful false com.
        /// </summary>
        public static string StFalseComTooltip {
            get {
                return ResourceManager.GetString("StFalseComTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKED IN 1ST NIGHT:.
        /// </summary>
        public static string StFnChecked {
            get {
                return ResourceManager.GetString("StFnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players which are often checked in the first night.
        /// </summary>
        public static string StFnCheckedTooltip {
            get {
                return ResourceManager.GetString("StFnCheckedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KILLED IN 1ST NIGHT:.
        /// </summary>
        public static string StFnKilled {
            get {
                return ResourceManager.GetString("StFnKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players which are often killed in the first night.
        /// </summary>
        public static string StFnKilledTooltip {
            get {
                return ResourceManager.GetString("StFnKilledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOULS:.
        /// </summary>
        public static string StFouls {
            get {
                return ResourceManager.GetString("StFouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVERAGE FOULS IN GAME:.
        /// </summary>
        public static string StFoulsAverage {
            get {
                return ResourceManager.GetString("StFoulsAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players with best average count of fouls in game.
        /// </summary>
        public static string StFoulsAverageTooltip {
            get {
                return ResourceManager.GetString("StFoulsAverageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fouls count.
        /// </summary>
        public static string StFoulsTooltip {
            get {
                return ResourceManager.GetString("StFoulsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES COUNT LEADERS:.
        /// </summary>
        public static string StGames {
            get {
                return ResourceManager.GetString("StGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders by total games count.
        /// </summary>
        public static string StGamesTooltip {
            get {
                return ResourceManager.GetString("StGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of games with guessing stage.
        /// </summary>
        public static string StGuessingTooltip {
            get {
                return ResourceManager.GetString("StGuessingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYERS:.
        /// </summary>
        public static string StPlayers {
            get {
                return ResourceManager.GetString("StPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total players count.
        /// </summary>
        public static string StPlayersTooltip {
            get {
                return ResourceManager.GetString("StPlayersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string StRedLabel {
            get {
                return ResourceManager.GetString("StRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string StRedSlice1 {
            get {
                return ResourceManager.GetString("StRedSlice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wins.
        /// </summary>
        public static string StRedSlice2 {
            get {
                return ResourceManager.GetString("StRedSlice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season table doesn&apos;t exists.
        /// </summary>
        public static string StSeasonError {
            get {
                return ResourceManager.GetString("StSeasonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEASON STATISTICS.
        /// </summary>
        public static string StSeasonTitle {
            get {
                return ResourceManager.GetString("StSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series table doesn&apos;t exists.
        /// </summary>
        public static string StSeriesError {
            get {
                return ResourceManager.GetString("StSeriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIES STATISTICS.
        /// </summary>
        public static string StSeriesTitle {
            get {
                return ResourceManager.GetString("StSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHERIFF WINS:.
        /// </summary>
        public static string StSheriffWins {
            get {
                return ResourceManager.GetString("StSheriffWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders by best win/lose ratio when playing as Sheriff.
        /// </summary>
        public static string StSheriffWinsTooltip {
            get {
                return ResourceManager.GetString("StSheriffWinsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE CHECKS:.
        /// </summary>
        public static string StThreeZv {
            get {
                return ResourceManager.GetString("StThreeZv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count of games where sheriff made three succesful checks in a row.
        /// </summary>
        public static string StThreeZvTooltip {
            get {
                return ResourceManager.GetString("StThreeZvTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL GAMES:.
        /// </summary>
        public static string StTotalGames {
            get {
                return ResourceManager.GetString("StTotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUESSING: .
        /// </summary>
        public static string StUgadPart1 {
            get {
                return ResourceManager.GetString("StUgadPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES.
        /// </summary>
        public static string StUgadPart2 {
            get {
                return ResourceManager.GetString("StUgadPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week table doesn&apos;t exists.
        /// </summary>
        public static string StWeekError {
            get {
                return ResourceManager.GetString("StWeekError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK STATISTICS.
        /// </summary>
        public static string StWeekTitle {
            get {
                return ResourceManager.GetString("StWeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN/LOSE RATIO:.
        /// </summary>
        public static string StWinLoseRatio {
            get {
                return ResourceManager.GetString("StWinLoseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders of the win/lose ratio.
        /// </summary>
        public static string StWinLoseRatioTooltip {
            get {
                return ResourceManager.GetString("StWinLoseRatioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechBlack.
        /// </summary>
        public static string TechBlackHeader {
            get {
                return ResourceManager.GetString("TechBlackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Black Win.
        /// </summary>
        public static string TechBlackLabel {
            get {
                return ResourceManager.GetString("TechBlackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of technical black wins.
        /// </summary>
        public static string TechBlackTooltip {
            get {
                return ResourceManager.GetString("TechBlackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechRed.
        /// </summary>
        public static string TechRedHeader {
            get {
                return ResourceManager.GetString("TechRedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Red Win.
        /// </summary>
        public static string TechRedLabel {
            get {
                return ResourceManager.GetString("TechRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of technical red wins.
        /// </summary>
        public static string TechRedTooltip {
            get {
                return ResourceManager.GetString("TechRedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three checks.
        /// </summary>
        public static string ThreeZvButton {
            get {
                return ResourceManager.GetString("ThreeZvButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Zv.
        /// </summary>
        public static string ThreeZvHeader {
            get {
                return ResourceManager.GetString("ThreeZvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of successful three checks when sheriff.
        /// </summary>
        public static string ThreeZvTooltip {
            get {
                return ResourceManager.GetString("ThreeZvTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMER.
        /// </summary>
        public static string TimerButton {
            get {
                return ResourceManager.GetString("TimerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min.
        /// </summary>
        public static string TimerLong {
            get {
                return ResourceManager.GetString("TimerLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string TimerReset {
            get {
                return ResourceManager.GetString("TimerReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 sec.
        /// </summary>
        public static string TimerShort {
            get {
                return ResourceManager.GetString("TimerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START/STOP.
        /// </summary>
        public static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.
        /// </summary>
        public static string TotalEnd {
            get {
                return ResourceManager.GetString("TotalEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guessing.
        /// </summary>
        public static string UgadaykaLabel {
            get {
                return ResourceManager.GetString("UgadaykaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting:.
        /// </summary>
        public static string VotingLabel {
            get {
                return ResourceManager.GetString("VotingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        public static string WeekButton {
            get {
                return ResourceManager.GetString("WeekButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week statistic:.
        /// </summary>
        public static string WeekStat {
            get {
                return ResourceManager.GetString("WeekStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinBlack.
        /// </summary>
        public static string WinBlackHeader {
            get {
                return ResourceManager.GetString("WinBlackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of wins while playing role of a Black.
        /// </summary>
        public static string WinBlackTooltip {
            get {
                return ResourceManager.GetString("WinBlackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinDon.
        /// </summary>
        public static string WinDonHeader {
            get {
                return ResourceManager.GetString("WinDonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of wins while playing role of a Don.
        /// </summary>
        public static string WinDonTooltip {
            get {
                return ResourceManager.GetString("WinDonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string WinHeader {
            get {
                return ResourceManager.GetString("WinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRed.
        /// </summary>
        public static string WinRedHeader {
            get {
                return ResourceManager.GetString("WinRedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of wins while playing role of a Red.
        /// </summary>
        public static string WinRedTooltip {
            get {
                return ResourceManager.GetString("WinRedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRow.
        /// </summary>
        public static string WinRowHeader {
            get {
                return ResourceManager.GetString("WinRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series of wins in a row.
        /// </summary>
        public static string WinRowTooltip {
            get {
                return ResourceManager.GetString("WinRowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinSh.
        /// </summary>
        public static string WinSheriffHeader {
            get {
                return ResourceManager.GetString("WinSheriffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of wins while playing role of a Sheriff.
        /// </summary>
        public static string WinSheriffTooltip {
            get {
                return ResourceManager.GetString("WinSheriffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins count.
        /// </summary>
        public static string WinTooltip {
            get {
                return ResourceManager.GetString("WinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong False Com number.
        /// </summary>
        public static string WrongFalseComMessage {
            get {
                return ResourceManager.GetString("WrongFalseComMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong nicks entered.
        /// </summary>
        public static string WrongNicksMessage {
            get {
                return ResourceManager.GetString("WrongNicksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in game results.
        /// </summary>
        public static string WrongResultsMessage {
            get {
                return ResourceManager.GetString("WrongResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in player&apos;s roles.
        /// </summary>
        public static string WrongRolesMessage {
            get {
                return ResourceManager.GetString("WrongRolesMessage", resourceCulture);
            }
        }
    }
}
